mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('student/', include('student.urls')),
    path('fin/', include('money.urls'))
]

money/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.money_home, name='money_home'),
    path('create', views.money_create, name='money_create'),
    path('<str:id>', views.money_detail, name='money_detail'),
    path('<str:id>/edit', views.money_edit, name='money_edit'),
]

student/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.student_home, name='student_home'),
    path('create', views.student_create, name='student_create'),
    path('<str:id>', views.student_detail, name='student_detail'),
    path('<str:id>/edit', views.student_edit, name='student_edit'),
]

student/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.

class Studentinfo(models.Model):
  def __str__(self):
    return self.id + '  --  ' +self.name
  SCH_YEAR_CHOICES = [
        ('1', '초등학교 1학년'),
        ('2', '초등학교 2학년'),
        ('3', '초등학교 3학년'),
        ('4', '초등학교 4학년'),
        ('5', '초등학교 5학년'),
        ('6', '초등학교 6학년'),
        ('7', '중학교 1학년'),
        ('8', '중학교 2학년'),
        ('9', '중학교 3학년'),
        ('10', '고등학교 1학년'),
        ('11', '고등학교 2학년'),
        ('12', '고등학교 3학년'),
    ]

  PAY_METHOD = [
    ('noty', '미정'),
    ('cash', '현금결제(영수증X)'),
    ('crsp', '현금결제(영수증O)'),
    ('card', '카드결제'),
    ('zero', '제로페이')
  ]
  id = models.CharField(max_length=4, primary_key=True)
  name = models.CharField(max_length=50, null=True, blank=True)
  regi_date = models.DateField(auto_now=False, auto_now_add=False, null=True, blank=True, default=now)
  due_date = models.DateField(auto_now=False, auto_now_add=False, null=True, blank=True)
  sch_year = models.CharField(max_length=50, choices=SCH_YEAR_CHOICES, default=None, null=True)
  phone = models.CharField(max_length=11, null=True, blank=True)
  due = models.IntegerField(null=True, blank=True)
  payment_method = models.CharField(max_length=50, choices=PAY_METHOD, default=None, null=True)
  card_number = models.CharField(max_length=20, null=True, blank=True)
  card_bank = models.CharField(max_length=10, null=True, blank=True)
  memo = models.TextField(null=True, blank=True)

  def make_id(self):
    idlist=[]
    if Studentinfo.objects.last():
      for i in Studentinfo.objects.all():
        idlist.append(i.id)
      self.id = "%04d"%(int(max(idlist)) + 1)
      print(idlist)
    else:
      self.id = "0000"

  

student/forms.py
from django.forms import ModelForm
from django import forms
from .models import Studentinfo
import datetime as dt

class StudentForm(ModelForm):
  name = forms.CharField(max_length=10, required=True, label='이름', error_messages={'required': '이름을 입력해 주세요'})
  regi_date = forms.DateTimeField(label='등록일', widget=forms.DateInput(attrs={'type': 'date'}), initial=dt.datetime.now())
  due_date = forms.DateTimeField(label='회비일', widget=forms.DateInput(attrs={'type': 'date'}), initial=dt.datetime.now())
  sch_year = forms.ChoiceField(label='학년', choices=Studentinfo.SCH_YEAR_CHOICES)
  phone = forms.CharField(max_length=20, label='연락처', required=False)
  payment_method = forms.ChoiceField(label='결제 수단', choices=Studentinfo.PAY_METHOD, widget= forms.Select(attrs={'onchange':'changeSelect(this)'}))
  memo = forms.CharField(widget=forms.Textarea,required=False)
  due = forms.IntegerField(label='회비',required=False)
  card_number = forms.CharField(label='카드 번호',required=False)
  card_bank = forms.CharField(label='은행',required=False)
  class Meta:
    
    
    model = Studentinfo
    fields = '__all__'
    exclude = ['id']
 
  
class StudentEditForm(ModelForm):
  name = forms.CharField(max_length=10, required=True, label='이름', error_messages={'required': '이름을 입력해 주세요'})
  regi_date = forms.DateTimeField(label='등록일', widget=forms.DateInput(attrs={'type': 'date'}))
  due_date = forms.DateTimeField(label='회비일', widget=forms.DateInput(attrs={'type': 'date'}))
  sch_year = forms.ChoiceField(label='학년', choices=Studentinfo.SCH_YEAR_CHOICES)
  phone = forms.CharField(max_length=20, label='연락처', required=False)
  payment_method = forms.ChoiceField(label='결제 수단', choices=Studentinfo.PAY_METHOD, widget= forms.Select(attrs={'onchange':'changeSelect(this)'}))
  memo = forms.CharField(widget=forms.Textarea,required=False)
  due = forms.IntegerField(label='회비',required=False)
  card_number = forms.CharField(label='카드 번호',required=False)
  card_bank = forms.CharField(label='은행',required=False)
  class Meta:
    
    
    model = Studentinfo
    exclude = ['id']
    fields = '__all__'

student/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from .models import *
from .forms import *
from money.models import *

# Create your views here.


def student_home(request):
  if request.method == 'POST':
    student_del = Studentinfo.objects.get(id=request.POST.get('stu_id'))
    student_del.delete()
    return redirect('student_home')
  
  student = Studentinfo.objects.all()

  content = {'student': student}
  return render(request, 'student/student_home.html', content)


def student_create(request):
  form = StudentForm()
  if request.method == 'POST':
    form = StudentForm(request.POST)
    if form.is_valid():
      obj = form.save(commit=False)
      obj.make_id()
      obj.save()
         
      return redirect('student_home')
  content = {'form':form}
  return render(request, 'student/student_create.html', content)

def student_detail(request, id):
  student = Studentinfo.objects.get(id=id)
  money = Money.objects.filter(student=student)
  content = {'student':student, 'money':money}
  return render(request, 'student/student_detail.html', content)

def student_edit(request, id):
  student = Studentinfo.objects.get(id=id)
  
  if request.method == 'POST':
    form = StudentEditForm(request.POST, instance=student)
    if form.is_valid():
      student = form.save(commit=False)
      student.save()
         
      return redirect('student_home')
  else:
    form = StudentEditForm(instance=student)
  content = {'student':student, 'form':form}
  return render(request, 'student/student_create.html', content)

student/templates/student/student_create.html
{% extends 'navbar.html' %}
{% load static %}

{% block title %}학생 추가{% endblock title %}

{% block content %}
  <div>
    <form action="" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <!--as_p는 더 보기좋게만들어줌-->
      {{forms.error}}
      <input type="submit" value='submit'>
    </form>
  </div>
  <script src='{% static 'js/student/student_edit.js' %}'></script>
{% endblock content %}

student/templates/student/student_detail.html
{% extends 'navbar.html' %}
{% load humanize %}
{% block title %}학생 상세 정보{% endblock title %}
{% block content %}

  아이디 :
  {{student.id}}<br>
  이름 :
  {{student.name}}<br>
  학년 :
  {{student.get_sch_year_display}}<br>
  등록일 :
  {{student.regi_date|date:'Y-m-d'}}<br>
  연락처 :
  {{student.phone}}<br>
  회비일 :
  {{student.due_date|date:'Y-m-d'}}
  <br>
  회비 :
  {{student.due}}<br>
  결제수단 :

  {{student.get_payment_method_display}}<br>
  {% if student.payment_method == 'card' %}
    은행 :
    {{student.card_bank}}<br>
    카드 번호 :
    {{student.card_number}}<br>
  {% endif %}
  메모 :
  {{student.memo}}<br>

  <button type="button" onclick="location.href='{{student.id}}/edit' ">학생 정보 수정</button>

  <table border="1" width="95%" align="center">
    <colgroup>
      <col span="1" width="15%">
      <col span="1" width="15%">
      <col span="1" width="15%">
      <col span="1" width="15%">
      <col span="1" width="15%">
      <col span="1" width="15%">

    </colgroup>
    <tr align="center">
      <p>
        <td colspan="6" span="span">결제 목록</td>
      </p>
    </tr>
    <tr>
      <td>월</td>
      <td>입금일</td>
      <td>승인일</td>
      <td>금액</td>
      <td>결제수단</td>
      <td>입금 확인</td>

    </tr>

    {% for i in money %}
      <tr onclick="window.location='/fin/{{i.id}}';">
        <td>{{i.pay_month}}월</td>

        <td>{{i.pay_date|date:'Y-m-d'}}</td>
        <td>{{i.get_date|date:'Y-m-d'}}</td>
        <td>{{i.due|intcomma}}원</td>
        <td>{{i.get_payment_method_display}}</td>
        <td>
          {% if i.pay_check %}
            <p>결제 완료</p>
          {% else %}
            <p style='color:red'>결제 미완료</p>
          {% endif %}
          {% if i.get_check %}
            <p>승인 완료</p>
          {% else %}
            <p style='color:red'>승인 미완료</p>
          {% endif %}
        </td>
      </tr>
    {% endfor %}

  </table>
{% endblock content %}

student/templates/student/student_home.html
{% extends 'navbar.html' %}
{% load static %}

{% block title %}학생 목록{% endblock title %}

{% block content %}
  <!DOCTYPE html>
  <html lang="en">
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel"></h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body"></div>
          <form action="." method="post" id='delete_form'>
            {% csrf_token %}
            <div class="modal-footer">
              <button form='delete_form' name='stu_id' type="submit" class="btn btn-default" data-dismiss="">데이터 삭제</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- Modal -->

    <head>
      <meta charset="UTF-8"/>
      <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <link rel="stylesheet" href="{% static 'css/student/student_home.css'%}"/>
      <title>이루마</title>
    </head>

    <body>
      <div class="all">
        <table id="mainlist">
          <colgroup>
            <col span="1" width="12%">
            <col span="1" width="25%">
            <col span="1" width="18%">
            <col span="1" width="18%">
            <col span="1" width="25%">

          </colgroup>
          <tr class="list_title">
            <td class="list">이름</td>
            <td class="list">학년</td>
            <td class="list">회비일</td>
            <td class="list">등록일</td>
            <td class='list'>연락처</td>
          </tr>
          {% for i in student %}
            <tr>

              <td onclick="window.location='{{i.id}}';" class="sublist">{{i.name}}</td>
              <td onclick="window.location='{{i.id}}';" class="sublist">{{i.get_sch_year_display}}</td>
              <td onclick="window.location='{{i.id}}';" class="sublist">{{i.due_date|date:'Y-m-d'}}</td>
              <td onclick="window.location='{{i.id}}';" class="sublist">{{i.regi_date|date:'Y-m-d'}}</td>
              <td onclick="window.location='{{i.id}}';" class="sublist">{{i.phone}}</td>
              <td class="sublist remove">
                <button type="button" id='{{i.id}}' value='{{i.name}}' onclick='reply_click(this)' class="remove_btn" data-toggle="modal" data-target="#myModal">
                  삭제
                </button>

              </td>
            </tr>
          {% endfor %}

        </table>
        <input onclick="location.href='create' " class="add" type="button" value="학생추가"/>
      </div>
    </body>
    <script src='{% static 'js/delete_modal.js' %}'></script>

  </html>
{% endblock content %}